name: CI

on:
  push:
    branches: ["main", "master"]
    paths:
      - 'roman-number-cont-deliv/**'
  pull_request:
    types: [opened, reopened]
    branches: ["main", "master"]
    paths:
      - 'roman-number-cont-deliv/**'
    
permissions:
  contents: read
  pages: write
  id-token: write    

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./roman-number-cont-deliv
    steps:
      - uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
        
  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ./roman-number-cont-deliv
    steps:
      - uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm test
      
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./roman-number-cont-deliv
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './roman-number-cont-deliv/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
